### ISSUE TITLE
BugCheck (DRIVER_POWER_STATE_FAILURE)

### ISSUE THREAD

**Issue by MrRocketFX** [ViGEm/BthPS3#41] opened 2022-03-23 19:10 UTC
### Can't provide more as the mem dump is 1.2GB
```
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

DRIVER_POWER_STATE_FAILURE (9f)
A driver has failed to complete a power IRP within a specific time.
Arguments:
Arg1: 0000000000000003, A device object has been blocking an IRP for too long a time
Arg2: ffffaa06b8bab840, Physical Device Object of the stack
Arg3: fffff8055a272750, nt!TRIAGE_9F_POWER on Win7 and higher, otherwise the Functional Device Object of the stack
Arg4: ffffaa06afb99560, The blocked IRP

Debugging Details:
------------------

Unable to load image \SystemRoot\System32\drivers\BthPS3.sys, Win32 error 0n2

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 2967

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 4005

    Key  : Analysis.Init.CPU.mSec
    Value: 765

    Key  : Analysis.Init.Elapsed.mSec
    Value: 48473

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 95

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1


FILE_IN_CAB:  MEMORY.DMP

BUGCHECK_CODE:  9f

BUGCHECK_P1: 3

BUGCHECK_P2: ffffaa06b8bab840

BUGCHECK_P3: fffff8055a272750

BUGCHECK_P4: ffffaa06afb99560

DRVPOWERSTATE_SUBCODE:  3

DRIVER_OBJECT: ffffaa06ac72be40

IMAGE_NAME:  BthPS3.sys

MODULE_NAME: BthPS3

FAULTING_MODULE: fffff8055c1f0000 BthPS3

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

PROCESS_NAME:  System

STACK_TEXT:  
fffff805`5a272718 fffff805`56b60157     : 00000000`0000009f 00000000`00000003 ffffaa06`b8bab840 fffff805`5a272750 : nt!KeBugCheckEx
fffff805`5a272720 fffff805`56b60071     : ffffaa06`b8687438 00000000`00000000 ffffaa06`b2ab7600 00000000`00000000 : nt!PopIrpWatchdogBugcheck+0xdf
fffff805`5a272790 fffff805`56881702     : ffffaa06`b8687470 fffff805`51977180 fffff805`51977180 00000000`00000002 : nt!PopIrpWatchdog+0x31
fffff805`5a2727e0 fffff805`56899add     : 00000000`00000000 00000000`00000000 00000000`00140001 00000000`003d1e14 : nt!KiProcessExpiredTimerList+0x172
fffff805`5a2728d0 fffff805`569fb18e     : 00000000`00000000 fffff805`51977180 fffff805`57326a00 ffffaa06`c32c50c0 : nt!KiRetireDpcList+0x5dd
fffff805`5a272b60 00000000`00000000     : fffff805`5a273000 fffff805`5a26c000 00000000`00000000 00000000`00000000 : nt!KiIdleLoop+0x9e


STACK_COMMAND:  .cxr; .ecxr ; kb

FAILURE_BUCKET_ID:  0x9F_3_IMAGE_BthPS3.sys

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {328a30da-bacc-a428-20ed-22a427c03a3c}

Followup:     MachineOwner
---------
```

**Comment by nefarius** [comment] 2022-03-23 19:12
People, seriously, use the search function... Closed as duplicate of #19

**Closed by nefarius** 2022-03-23 19:12 UTC
